input_file: "input.mp4"
output_file: "output.mp4"
time_interval: 2 # in seconds

augmentation_parameters:
  scale_factor:
    low: 0.3
    high: 0.7

  blur_radius:
    low: 3
    high: 7

  saturation_factor:
    low: 1.0
    high: 1.5
